# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Get < Formula
  desc "Software to create fast and easy drum rolls."
  homepage "https://example.com/"
  version "0.1.2"
  license "MIT"

  depends_on "git"

  on_macos do
    on_intel do
      url "https://github.com/AIO-Develope/get/releases/download/0.1.2/get_0.1.2_darwin_amd64"
      sha256 "55fc447521e95f41ed93e68d5476eb1352cbca58da690872ca0c0945e6963cdb"

      def install
        bin.install "get"
      end
    end
    on_arm do
      url "https://github.com/AIO-Develope/get/releases/download/0.1.2/get_0.1.2_darwin_arm64"
      sha256 "4a83cc020ab26fbe2b89e942ad4d357aaac7fd7542a19ac3f2e91cca36bf3763"

      def install
        bin.install "get"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AIO-Develope/get/releases/download/0.1.2/get_0.1.2_linux_amd64"
        sha256 "c8c66e15729115a05828ff30302095e9edb0e5fceb11791f56c77d7604f512bb"

        def install
          bin.install "get"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AIO-Develope/get/releases/download/0.1.2/get_0.1.2_linux_arm64"
        sha256 "5a56daabc8f5e0b915f0698c36a2c85666225e632e98e52f775e7618e36d17e3"

        def install
          bin.install "get"
        end
      end
    end
  end

  conflicts_with "svn"
  conflicts_with "bash"

  def caveats
    <<~EOS
      How to use this binary
    EOS
  end
end
