# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Get < Formula
  desc "Software to create fast and easy drum rolls."
  homepage "https://example.com/"
  version "0.1.2"
  license "MIT"

  depends_on "git"

  on_macos do
    on_intel do
      url "https://github.com/AIO-Develope/get/releases/download/0.1.2/get_0.1.2_darwin_amd64"
      sha256 "d2450bd0ab56ebaea7987ceeca2b8b6f288c9b8f7a1b003df1a97331a50c9d2d"

      def install
        bin.install "get"
      end
    end
    on_arm do
      url "https://github.com/AIO-Develope/get/releases/download/0.1.2/get_0.1.2_darwin_arm64"
      sha256 "12d1803ad20b8afc723ce19de579503e78c02426647e502146b2165a5afa1993"

      def install
        bin.install "get"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AIO-Develope/get/releases/download/0.1.2/get_0.1.2_linux_amd64"
        sha256 "3b21d99ccce9dafc49564423025ba17b4e02258439c1270b7624036fe8dee036"

        def install
          bin.install "get"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AIO-Develope/get/releases/download/0.1.2/get_0.1.2_linux_arm64"
        sha256 "c4f3092d49f01dd2c040dc55af67778cc91877611fdeca1d28eeec2076c891a5"

        def install
          bin.install "get"
        end
      end
    end
  end

  conflicts_with "svn"
  conflicts_with "bash"

  def caveats
    <<~EOS
      How to use this binary
    EOS
  end
end
